server:
  port: 8084

spring:
  application:
    name: fulfillment-service

  # Kafka Settings
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fulfillment-group
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false